name = "rpc-racer"
main = "src/index.ts"
compatibility_date = "2026-04-21"
workers_dev = false

routes = [
  { pattern = "rpc.steer.fun", custom_domain = true },
  { pattern = "evm.stupidtech.net", custom_domain = true },
]

[[durable_objects.bindings]]
name = "METRICS_DO"
class_name = "MetricsDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MetricsDurableObject"]

[vars]
CHAINLIST_RPCS_URL = "https://chainlist.org/rpcs.json"
ALCHEMY_NETWORK_CONFIG_URL = "https://app-api.alchemy.com/trpc/config.getNetworkConfig"
DEFAULT_TIMEOUT_MS = "2000"
